[build]
  publish = "dist/browser"
  command = "ng build --prod"

[context.production.environment]
  # Add any environment variables you need for your production build
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
